# Generated by Django 5.1.7 on 2025-03-31 15:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'blank': True}), 1: ('wagtail.images.blocks.ImageBlock', [], {})}),
        ),
    ]
