# Generated by Django 5.1.7 on 2025-03-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='trailer',
            field=models.TextField(blank=True),
        ),
    ]
